### ISSUE TITLE
Support redux-saga

### ISSUE THREAD

**Issue by acourtiol** [societe-generale/react-loopback-generator#49]
Hello,

I had some weeks ago a great discussion with a fellow of mine @jdrouet about the advantages of redux-saga. As the weeks went by I agreed with him and the idea to use it in our own generator came by. I spoke about it with @Abdelhamidhenni and other lead developers from my teams that are interested aswell.

I would be very interested into having your point of view on this @msalettes @daniel-jorge @jeanlucc @ghamaide.

Alexandre

**Comment by jeanlucc** [comment]
@acourtiol As it is a societe generale matter, I prefer let people of societe generale take this decision.

**Comment by acourtiol** [comment]
@jeanlucc it's not about decision as of now, it's about giving opinions, pros and cons. Everyone is wellcome on this 😄

**Comment by acourtiol** [comment]
@HugoCapocci I forgot to tag you but your feedbacks are very wellcomed here 👍

**Comment by ghamaide** [comment]
@acourtiol redux-thunk works fine but has IMO, 2 disadvantages vs redux-saga

1. Harder to test (you need to mock the store, mock the fetch API, ...)
2. More verbose (in larger projects it becomes harder to maintain)

However, redux-saga is trickier than thunk. You need to understand generators (https://davidwalsh.name/es6-generators).

**Comment by HugoCapocci** [comment]
I have to test redux-saga (and manipulate generators) on my own to make my opinion, but from what I have read about redux-saga, I agree with @ghamaide

**Comment by acourtiol** [comment]
From a lot of readings and market reviews it seems that Saga is kind of the "market standard" today but yes it's a little bit more complex to understand at first but on the long term view it shows a lot of advantages.
